{% set name = "simplekv" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d951549bb3d9dbe944ae3308fde66702c4f0478c94c785139a37da4129cd8882

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simplekv

about:
  home: http://simplekv.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple key-value store for binary data.'
  dev_url: https://github.com/mbr/simplekv

extra:
  recipe-maintainers:
    - xhochy
