{% set name = "simplekv" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61e6a8c8d53154033c8f97131418d0e31159d5d959a94b8f0fe5587da2d472b1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simplekv

about:
  home: http://simplekv.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A simple key-value store for binary data.'
  dev_url: https://github.com/mbr/simplekv

extra:
  recipe-maintainers:
    - xhochy
