travis:
  secure:
    BINSTAR_TOKEN: YovUVVUS7XHlhlAN3ldipwmQdAW5HchXCzt2Sy7/3gC4Oljtoub/kfTtz9JXlp+Tpgi6Zd4Jyr2/R/hX+fIcW8y27uiH9HqBfx8zsc0iWAAIFd2aSrELXLxxOA3Zug8eAnJRh3ocQimGFPXuZhlhuvE5PzOapkB9mWmYPOm9qnK2Ed+trHzvdOWKn3am2ABU2+quExiDS5y56+kEglhWop7NlE2Ved9zy9W4CO/Tpt910vBLp1Hn/GvTL6Q6xwWqgIzekHJJBCZnKBE5tzUf0zrObdwWkpEYU9fhjfPHAY3A/sKmxE1XJaESsVqFpt+lzwSG7HLfxoQ73WXr8EIGXg44I1lAzBfVC8XiIgjEDDC+OHqxH3KrP4XpRDuAtiXk50D2xTUfBsxcqSlB3K0xf7QIxdIFETo+v2t7tRQ/wZO9ANXHc8+iSs9NGaYB7iNR3KyRrRQQJXy1AupGZSlVGOJQChREjUEjP770cuv5snYxNH6cDMZAq8ofOhbPqYJgdoDjGmdQI3YprjbDMs0ItJX18ilbfXugbZde8UTHfd7nTbSrJ94puQ/xM+oSAg1BXqWuJ9H4gMGAPLrKpRZEQLT1tKRhUS7uLPX1Y3OoaLfvTmRTS+nsVeUcQUtChNkE/WQho30tITTihGHtV78J25R36mPbdeuswmCBocqTjrA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
